server:
  port: 8080

spring:
  application:
    name: investment-tracker

  mongodb:
    uri: mongodb+srv://pthirumalayadav_db_user:1a8dtlaj5qBH3qR9@it-staging.6fu8nvy.mongodb.net/?retryWrites=true&w=majority
    database: it-staging

# RabbitMQ configuration
  rabbitmq:
    username: ejcdabas
    password: GAP558hOcfxjgBiTSM2dFifoXYxt57Rx
    addresses: amqps://ejcdabas:GAP558hOcfxjgBiTSM2dFifoXYxt57Rx@prawn-01.rmq.cloudamqp.com/ejcdabas
